### ISSUE TITLE
US_013_Página de Inicio

### ISSUE THREAD

**Issue by LautiCarracedo** [pgPilfs/pil-money-g4c-pil-money-g4c#30]
Como usuario quiero ver una página de inicio con un encabezado fijo y un pie de página para poder navegar y visualizar de manera general las acciones más importante de la plataforma.

**Comment by agusprogramfile** [comment]
> Como usuario quiero ver una página de inicio con un encabezado fijo y un pie de página para poder navegar y visualizar de manera general las acciones más importantes de la plataforma.
